spring:
  application:
    name: WeatherForecastApplication

server:
  port: 8080

rapidApi:
  baseUri: "https://forecast9.p.rapidapi.com/rapidapi/forecast/"
  summaryUriSuffix: "{locationName}/summary/"
  hourlyUriSuffix: "{locationName}/hourly/"
  headers:
    apiKey: ${WEATHER_FORECAST_API_KEY}
    apiHost: "forecast9.p.rapidapi.com"


